provide_settings:
  llm:
    provider: "DeepSeek"
    config:
      model: "deepseek-chat"
      api_key: "sk-123e9b32a0a34fd48f623c1429241bd8"
      base_url: "https://api.deepseek.com/v1"

  embedding:
    provider: "QwenEmbedding"
    config:
      model: "text-embedding-v4"

  file_loader:
    provider: "SelfLoader"
    config: {}

#    provider: "PDFLoader"
#    config: {}

  web_crawler:
    provider: "FireCrawlCrawler"
    config: {}

  vector_db:
    provider: "Qdrant"
    config:
      default_collection: "my_collection"
      path: "./qdrant.db"

query_settings:
  max_iter: 3

load_settings:
  chunk_size: 1500
  chunk_overlap: 100
